### ISSUE TITLE
Install fails with composer option

### ISSUE THREAD

**Issue by WillPS1989** [paliarush/vagrant-magento#137]
Hi there,
Been trying for days to get this working. I initially installed via git clone, and it all worked just dandy. When I choose Composer however, the installation just hangs. I've tried manually installing via the CLI after aborting the init_project script, and the installation hangs at 

```
[Progress: 212 / 426]
Installing user configuration...
```

But I can't seem to get any further. I've tried disabling Xdebug completely and it still seems to be the same.

I can't figure out what's causing it to stall - especially since Git install seems to go through smoothly.

Host OS is Ubuntu 16.04.

Thanks in advance for any help.

**Comment by paliarush** [comment]
This looks like an issue with Magento installer script itself. Could you please try to follow http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install_ce.html to install it manually?


It works fine for me with default settings on OSX host:

```
checkout_source_from: "composer"

composer_project:
  # Current section used only if 'checkout_source_from' is set to 'composer'

  # [To apply changes: init_project.sh -fc]
  name: "magento/project-community-edition"
  # Make sure to specify valid keys for this repository in etc/composer/auth.json
  url: "https://repo.magento.com"
```

Could you please provide the same part of `etc/config.yaml` from your installation?

**Comment by paliarush** [comment]
Hi @WillPS1989 , if you still need to get this work, I would be glad to help. Please try my suggestions from the previous comment.

**Comment by WillPS1989** [comment]
Thanks Alex,
I'm giving it another go now, I'll write back with my results.

**Comment by WillPS1989** [comment]
Same story.

Install via init_project.sh stalls during the Magento installation
Opening the wizard via a browser stalls midway through setup
Manually installing via SSH also stalls.

Always stops at the 'Installing user configuration...' step

Here's that section of config.yaml
```
# [To apply changes: init_project.sh -fc] Possible values: git, composer
checkout_source_from: "composer"

composer_project:
  # Current section used only if 'checkout_source_from' is set to 'composer'

  # [To apply changes: init_project.sh -fc]
  name: "magento/project-community-edition"
  # Make sure to specify valid keys for this repository in etc/composer/auth.json
  url: "https://repo.magento.com"
```
