### ISSUE TITLE
Magento version

### ISSUE THREAD

**Issue by PieterCappelle** [paliarush/vagrant-magento#24]
Hi,

Today at Magento Imagine this github repository has been on multiple slides. I did an installation like described in the readme and everything is working fine. One issue: the default version after installation is v2.0. Magento2 is already on v2.0.4. How can this be fixed?

When updating: i get the message 'We're sorry, no components are available because you cloned the Magento 2 GitHub repository. You must manually update components as discussed in the Installation Guide.' > wouldn't it be better to work with the composer version? 

Thanks in advance!

**Comment by paliarush** [comment]
Hi @PieterCappelle, what you actually get by default is the latest `develop` branch of Magento 2 (https://github.com/magento/magento2). So it is even more fresh than v2.0.4.

If you need to get some specific version of Magento 2, please follow this step from [installation guide](https://github.com/paliarush/magento2-vagrant-for-developers#installation-steps):

> Optionally, copy etc/config.yaml.dist as etc/config.yaml and make necessary customizations

You can specify custom repositories for Magento CE and EE. Please take a look at my answer [here](https://github.com/paliarush/magento2-vagrant-for-developers/issues/19) it gives more details on what options can be configured.

**Comment by PieterCappelle** [comment]
Hi @paliarush, thanks for your response. Let's split up some answers.

1) Strange, my version after install is 2.0.0. This is my config.yaml file.

```
repository_url:
  ce: "git@github.com:magento/magento2.git"
  ee: ""
guest:
  # NFS will be used for folder synchronization on *nix and OSX hosts by default
  use_nfs: 1
  # Default is 2Gb, around 3Gb is necessary to run functional tests
  memory: 4096
  ip_address: "192.168.20.2"
  forwarded_ssh_port: 3116
environment:
  # If set to 0, PHP 5 will be installed
  use_php7: 1
  composer_prefer_source: 0
magento:
  host_name: "local.magento22"
  admin_frontname: "admin"
  language: "nl_NL"
  timezone: "Europe/Brussels"
  currency: "EUR"
  admin_user: "xxx"
  admin_password: "xxx"
```

2) You got any answer about the composer question, that's not so clear for me from the docs. Thanks in advance.
