### ISSUE TITLE
Cannot switch to EE using bash m-switch-to-ee 

### ISSUE THREAD

**Issue by LCIJJ** [paliarush/vagrant-magento#71]
I'm downloading EE from a private repo. Here's what the repo section of my config.yaml looks like.

```
repository_url:
  # [To apply changes: init-project -fc]
  ce: "https://github.com/magento/magento2.git "
  ee: "https://github.com/LCind/magento2ee.git"
```

From my host machine, executing `bash m-switch-to-ee` returns the following:

```
C:\Projects\vagrant-magento>bash m-switch-to-ee
+ [[ -f /c/Projects/vagrant-magento/lib/php/php.exe ]]
+ php_executable=php
+ echo php
+ [[ ! -f /c/Projects/vagrant-magento/magento2ce/magento2ee/app/etc/aliases_to_classes_map.json ]]
+ set +x
EE codebase is not available
```
